export const GET_ERRORS = 'GET_ERRORS';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_STATISTIC = 'GET_CURRENT_STATISTIC';
export const GET_CURRENT_COMPANIES_LIST = 'GET_CURRENT_COMPANIES_LIST';
export const GET_CURRENT_COMPANY = 'GET_CURRENT_COMPANY';
export const ADD_CARRIER = 'ADD_CARRIER';
export const  PREV_PATH = 'PREV_PATH';
