export const GET_ERRORS = 'GET_ERRORS';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_STATISTIC = 'GET_CURRENT_STATISTIC';
export const GET_CURRENT_COMPANIES_LIST = 'GET_CURRENT_COMPANIES_LIST';
export const GET_CURRENT_COMPANY = 'GET_CURRENT_COMPANY';
// driver
export const ADD__DRIVER = 'ADD_DRIVER';
